"""
sources_config.py - 모든 데이터 소스 중앙 설정
"""

ALL_SOURCES = [
    # ── 글로벌 컨설팅 ─────────────────────────────────────────
    {
        "name": "McKinsey & Company",
        "name_ko": "맥킨지",
        "category": "글로벌 컨설팅",
        "url": "https://www.mckinsey.com/kr/our-insights/mckinsey-insights",
        "logo_domain": "mckinsey.com",
        "type": "web_pdf",
        "description": "맥킨지 한국 인사이트 리포트",
    },
    {
        "name": "BCG",
        "name_ko": "보스턴컨설팅그룹",
        "category": "글로벌 컨설팅",
        "url": "https://www.bcg.com/capabilities/artificial-intelligence/insights",
        "logo_domain": "bcg.com",
        "type": "web_pdf",
        "description": "BCG AI 인사이트",
    },
    {
        "name": "Deloitte",
        "name_ko": "딜로이트",
        "category": "글로벌 컨설팅",
        "url": "https://www.deloitte.com/kr/ko/our-thinking/deloitte-insights.html",
        "logo_domain": "deloitte.com",
        "type": "web_pdf",
        "description": "딜로이트 인사이트",
    },
    {
        "name": "KPMG 경제연구원",
        "name_ko": "KPMG 경제연구원",
        "category": "글로벌 컨설팅",
        "url": "https://kpmg.com/kr/ko/insights/eri.html",
        "logo_domain": "kpmg.com",
        "type": "web_pdf",
        "description": "KPMG 경제연구원 리포트",
    },
    {
        "name": "KPMG AI Insight",
        "name_ko": "KPMG AI 인사이트",
        "category": "글로벌 컨설팅",
        "url": "https://kpmg.com/kr/ko/ai/kpmg-ai-insight.html",
        "logo_domain": "kpmg.com",
        "type": "web_pdf",
        "description": "KPMG AI 인사이트",
    },
    {
        "name": "PwC",
        "name_ko": "PwC 삼일회계법인",
        "category": "글로벌 컨설팅",
        "url": "https://www.pwc.com/kr/ko/insights/issue-brief.html",
        "logo_domain": "pwc.com",
        "type": "web_pdf",
        "description": "PwC Issue Brief",
    },
    {
        "name": "EY IT",
        "name_ko": "EY 한영 IT",
        "category": "글로벌 컨설팅",
        "url": "https://www.ey.com/ko_kr/services/technology",
        "logo_domain": "ey.com",
        "type": "web",
        "description": "EY 기술 서비스 인사이트",
    },
    {
        "name": "EY AI",
        "name_ko": "EY 한영 AI",
        "category": "글로벌 컨설팅",
        "url": "https://www.ey.com/ko_kr/services/ai",
        "logo_domain": "ey.com",
        "type": "web",
        "description": "EY AI 인사이트",
    },

    # ── 국내 연구기관 ─────────────────────────────────────────
    {
        "name": "IITP 주간기술동향",
        "name_ko": "정보통신기획평가원 주간기술동향",
        "category": "국내 연구기관",
        "url": "https://www.iitp.kr/web/lay1/program/S1T62C65/itfind/list.do",
        "logo_domain": "iitp.kr",
        "type": "pdf",
        "description": "IITP 주간기술동향 PDF",
    },
    {
        "name": "IITP ICT Brief",
        "name_ko": "정보통신기획평가원 ICT Brief",
        "category": "국내 연구기관",
        "url": "https://www.iitp.kr/web/lay1/program/S1T62C66/itfind/list.do",
        "logo_domain": "iitp.kr",
        "type": "pdf",
        "description": "IITP ICT Brief PDF",
    },
    {
        "name": "NIA",
        "name_ko": "한국지능정보사회진흥원",
        "category": "국내 연구기관",
        "url": "https://www.nia.or.kr/site/nia_kor/ex/bbs/List.do?cbIdx=25932",
        "logo_domain": "nia.or.kr",
        "type": "web_pdf",
        "description": "NIA AI·디지털 관련 보고서",
    },

    # ── 한국 대기업 IT ────────────────────────────────────────
    {
        "name": "Samsung SDS",
        "name_ko": "삼성SDS",
        "category": "한국 대기업",
        "url": "https://www.samsungsds.com/kr/insights/index.html",
        "logo_domain": "samsungsds.com",
        "type": "web",
        "description": "삼성SDS 인사이트",
    },
    {
        "name": "LG CNS",
        "name_ko": "LG CNS",
        "category": "한국 대기업",
        "url": "https://www.lgcns.com/kr/moa/insight.page_1",
        "logo_domain": "lgcns.com",
        "type": "web",
        "description": "LG CNS MOA 인사이트",
    },
    {
        "name": "SK AX",
        "name_ko": "SK AX",
        "category": "한국 대기업",
        "url": "https://www.skax.co.kr/insight/trends",
        "logo_domain": "skax.co.kr",
        "type": "web",
        "description": "SK AX 트렌드 인사이트",
    },
    {
        "name": "Hyundai AutoEver",
        "name_ko": "현대오토에버",
        "category": "한국 대기업",
        "url": "https://www.hyundai-autoever.com/kor/about/pr/insights/list.do",
        "logo_domain": "hyundai-autoever.com",
        "type": "web",
        "description": "현대오토에버 인사이트",
    },
    {
        "name": "Ackerton Partners",
        "name_ko": "에커튼파트너스",
        "category": "한국 대기업",
        "url": "https://www.ackerton.com/insightReport",
        "logo_domain": "ackerton.com",
        "type": "web_pdf",
        "description": "에커튼파트너스 인사이트 리포트",
    },

    # ── 플랫폼 테크 ───────────────────────────────────────────
    {
        "name": "Naver D2",
        "name_ko": "네이버 D2",
        "category": "플랫폼 테크",
        "url": "https://d2.naver.com/home",
        "logo_domain": "naver.com",
        "type": "rss",
        "rss_url": "https://d2.naver.com/d2.atom",
        "description": "네이버 기술 블로그",
    },

    # ── IT 미디어 ─────────────────────────────────────────────
    {
        "name": "IT조선",
        "name_ko": "IT조선",
        "category": "IT 미디어",
        "url": "https://it.chosun.com/news/articleList.html?sc_sub_section_code=S2N46",
        "logo_domain": "it.chosun.com",
        "type": "web",
        "description": "IT조선 AI/소프트웨어 뉴스",
    },
    {
        "name": "ZDNet Korea",
        "name_ko": "ZDNet Korea",
        "category": "IT 미디어",
        "url": "https://zdnet.co.kr/news/?lstcode=0020",
        "logo_domain": "zdnet.co.kr",
        "type": "web",
        "description": "ZDNet 소프트웨어 뉴스",
    },
    {
        "name": "전자신문",
        "name_ko": "전자신문",
        "category": "IT 미디어",
        "url": "https://m.etnews.com/news/section.html?id1=03",
        "logo_domain": "etnews.com",
        "type": "web",
        "description": "전자신문 IT 뉴스",
    },
    {
        "name": "인공지능신문",
        "name_ko": "인공지능신문",
        "category": "IT 미디어",
        "url": "https://www.aitimes.kr/",
        "logo_domain": "aitimes.kr",
        "type": "web",
        "description": "인공지능신문",
    },
    {
        "name": "AI타임즈",
        "name_ko": "AI타임즈",
        "category": "IT 미디어",
        "url": "https://www.aitimes.com/",
        "logo_domain": "aitimes.com",
        "type": "web",
        "description": "AI타임즈",
    },
]

# 카테고리별 색상
CATEGORY_COLORS = {
    "글로벌 컨설팅": "#7c3aed",
    "국내 연구기관": "#0891b2",
    "한국 대기업":   "#0284c7",
    "플랫폼 테크":   "#059669",
    "IT 미디어":     "#d97706",
}
